Week 7
Erkan-5Minds/CS50_Course pull request #11
Opened 2022-10-21 07:08 UTC by Erkan-5Minds

2022-10-21 13:27 UTC, DevBastiS requested changes

2022-10-21 13:27 UTC, DevBastiS commented on Week_7/movies/1.sql
> +WHERE year == 2008
A lot of missing EOFs here

2022-10-21 13:27 UTC, DevBastiS commented on Week_7/movies/3.sql
> +ORDER BY title
I would suggest to add an indent here like this:

```suggestion
SELECT title FROM movies
  WHERE year >= 2018
  ORDER BY title
```

Adapt this for all files.

2022-11-07 08:45 UTC, stefanluth commented on Week_7/songs/1.sql
> +SELECT name FROM songs;
Add EOFs :)

2022-11-07 10:25 UTC, DevBastiS approved these changes

2022-11-10 12:19 UTC, stefanluth approved these changes

2022-11-11 07:59 UTC, merged