WIP: Week 2
Erkan-5Minds/CS50_Course pull request #5
Opened 2022-08-08 12:50 UTC by Erkan-5Minds

2022-08-11 13:46 UTC, stefanluth reviewed
Try to remove the `.DS_Store` & `Week_2_Arrays/.vscode/c_cpp_properties.json` files :)

2022-08-15 06:22 UTC, DevBastiS commented
The title is still WIP (Work in Progress) so I am not sure if I should review here.

2022-09-08 06:46 UTC, MKrips requested changes
Remember to do what Stefan requested.

2022-09-08 06:46 UTC, MKrips commented on Week_2_Arrays/caesar/caesar.c
> +        printf("\n");
This should be indented 4 spaces, not 8.

2022-09-08 06:46 UTC, MKrips commented on Week_2_Arrays/readability/readability.c
> +    int senteces = 0;
```suggestion
    int sentences = 0;
```

2022-09-09 06:08 UTC, DevBastiS requested changes

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/caesar/caesar.c
> +    }
```suggestion
    }
    
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/caesar/caesar.c
> +
```suggestion
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/readability/readability.c
> +
```suggestion
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/readability/readability.c
> +
```suggestion
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/scrabble/scrabble.c
> +    }
```suggestion
    }

```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/scrabble/scrabble.c
> +    return 0;
```suggestion
        return 0;
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +    }
```suggestion
    }
    
```

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +    for (int i = 'A'; i < 'Z'; i++)
Always use {} notation

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +       if (isalpha(s[i]))
Always use {} notation

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +    if (len != 26)
Always use {} notation

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +        if (!isalpha(s[i]))
Always use {} notation

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +        if (freq[index] > 0)
Always use {} notation

2022-09-09 06:08 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +    }
```suggestion
    }
    
```

2022-09-12 09:46 UTC, DevBastiS requested changes

2022-09-12 09:46 UTC, DevBastiS commented on Week_2_Arrays/substitution/substitution.c
> +    }
Sill open

2022-09-12 10:48 UTC, DevBastiS requested changes

2022-09-12 10:48 UTC, DevBastiS commented on Week_2_Arrays/caesar/caesar.c
> +        if (!isdigit(argv[1][i]))
Always use {} notation

2022-09-12 10:50 UTC, DevBastiS commented on Week_2_Arrays/caesar/caesar.c
> +        if (!isdigit(argv[1][i]))
Still open

2022-09-12 11:02 UTC, DevBastiS requested changes
Fix Merge Conflicts

2022-09-12 12:31 UTC, DevBastiS approved these changes

2022-09-12 12:32 UTC, MKrips approved these changes

2022-09-12 12:32 UTC, merged