Week 3
Erkan-5Minds/CS50_Course pull request #6
Opened 2022-09-12 14:23 UTC by Erkan-5Minds

2022-09-13 07:25 UTC, DevBastiS requested changes

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +// Max number of candidates
Remove comments.

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +        }
Wrong indent.

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    bool CandidateIsCandidateToVote = strcmp(name, candidates[i].name) == 0;
```suggestion
    bool candidateIsCandidateToVote = strcmp(name, candidates[i].name) == 0;
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    if (CandidateIsCandidateToVote)
```suggestion
    if (candidateIsCandidateToVote)
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +}
```suggestion
}

```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +     }
Wrong indent

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +    }
Wrong indent

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +bool print_winner(void)
Wrond indents all over the place please fix then I will review again.

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +            if (preferences[pairs[j].winner][pairs[j].loser] > preferences[pairs[max].winner][pairs[max].loser])
Extract to speaking variable.

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 07:25 UTC, DevBastiS commented on Week_3/tideman/tideman.c
> +    }
```suggestion
    }
    
```

2022-09-13 12:36 UTC, stefanluth requested changes
Fix indents.

2022-09-13 12:36 UTC, stefanluth commented on Week_3/plurality/plurality.c
> +}
Missing return

2022-09-13 12:36 UTC, stefanluth commented on Week_3/runoff/runoff.c
> +    return false;
This function always returns false.

2022-09-14 06:20 UTC, DevBastiS requested changes

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +        printf("%s\n", candidates[i].name);
Wrong indent

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/plurality/plurality.c
> +    }
Still open

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +    }
Still open

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +    }
Still open

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +}
Still open

2022-09-14 06:20 UTC, DevBastiS commented on Week_3/runoff/runoff.c
> +}
Alot of wrong indents still here

2022-09-16 08:33 UTC, stefanluth requested changes
Fix indents :)

2022-09-16 08:33 UTC, stefanluth commented on Week_3/plurality/plurality.c
> +candidate candidates[MAX];
```suggestion
typedef struct
{
    string name;
    int votes;
} candidate;

candidate candidates[MAX];
```

2022-09-16 08:53 UTC, stefanluth approved these changes

2022-09-16 08:58 UTC, DevBastiS approved these changes

2022-09-16 08:58 UTC, merged